### ISSUE TITLE
[FR] Easy theming , logo and other features, similar to what `xaringanExtra` does

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/revealjs#101] opened 2021-08-23 16:11 UTC
It would be great to have an easy way to change theme of slides, logo and other features similar to what `xaringanExtra` .

Are there plans to add features that `xaringanExtra` offers to `revealjs`

````markdown
---
title: "Presentation Ninja"
subtitle: "with xaringan"
author: ""
date: ""
output:
  xaringan::moon_reader:
    css:  xaringan-themer.css
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      countIncrementalSlides: false
---



```{r xaringan-animate-css, echo=FALSE}
# xaringanExtra::use_animate_css() 
xaringanExtra::use_animate_all("slide_left") # this makes incremental not work  can we have incremental for all slides slides the same page as many bullet incremental points
xaringanExtra::use_progress_bar(color = "#0051BA", location = "bottom")
xaringanExtra::use_tile_view()
xaringanExtra::use_scribble()
```


```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#002B36",               # dark blue first slide
  background_color = "#002B36",         # dark dark blue next slides
  header_color = "white",     # light aqua green
  text_color = "white",       # white
  title_slide_background_color = "var(--base)",
  text_font_google = google_font("Kelly Slab"),
  header_font_google = google_font("Oleo Script")
)

```


```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_logo(
  image_url = "my_logo.png"
)
```
````

**Comment by jjallaire** [comment] 2021-08-23 16:19
Yes definitely. We are going to be working on an update to revealjs this fall that adds many of these features.

**Comment by cderv** [comment] 2021-09-17 13:37
This will be covered probably by #95 

The API won't be similar to **xaringanExtra** but it should be as easy, and it will be a common theming system across all type of output formats. 

I'll close this issue in favor of the other where we'll discuss the theming system. 

Thanks for the great suggestion !

**Comment by cderv** [comment] 2021-09-17 13:37
Duplicate of #95

**Closed by cderv** 2021-09-17 13:37 UTC
Labels: feature
