### ISSUE TITLE
reveal.js folder

### ISSUE THREAD

**Issue by nlhuong** [rstudio/revealjs#56] opened 2017-10-05 01:44 UTC
Reveal.js folder, e.g. "reveal.js-3.3.0.1" with all source reveal.js source code is generated in a "presentation_files" folder whenever a presentation is knitted in Rstudio. Is there a way to not download the reveal.js folder each time but specify a path to it? In such a way multiple presentations can use the same reveal.js folder.

**Comment by jjallaire** [comment] 2017-10-05 11:34
If you set `self_contained: false` in the YAML and use a `lib_dir` then all presentations within a single directory will use that same directory for dependencies (including revealjs). Docs on this are here: http://rmarkdown.rstudio.com/revealjs_presentation_format.html#document_dependencies

**Comment by cderv** [comment] 2021-09-16 13:57
Duplicate of #53. We'll keep the other one in the idea to allow using a custom revealjs download instead of the one included.

**Closed by cderv** 2021-09-16 13:57 UTC
Labels: question
