### ISSUE TITLE
Syntax Highlighting on `revealjs` slides incrementally?

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/revealjs#142] opened 2021-10-06 16:36 UTC
Is there a way to create syntax highlight on slides with `rmarkdown`?

According to the [revealjs website](https://revealjs.com/markdown/)  the following chunk code should highlight the syntax; however, it does not work in `rmarkdown`

````markdown
<section data-markdown>
  <textarea data-template>
    ```js [1-2|3|4]
    let a = 1;
    let b = 2;
    let c = x => 1 + 2 + x;
    c(3);
    ```
  </textarea>
</section>
````

**Comment by cderv** [comment] 2021-10-06 17:17
revealjs R package currently does not use the `revealHighlight` plugin from the documentation of reveal.js you are referring too. Pandoc does not use it and it would be a new feature to add in the R package. There is an issue to track this #118 

Currently, highlighting is based on Pandoc feature as with other formats (`html_document()`, `pdf_document()`, ...). 
So you can just use fenced backticks with attributes as you would do in other documents with R Markdown.

````markdown
```js
let a = 1;
let b = 2;
let c = x => 1 + 2 + x;
c(3);
```
````

Pandoc docs: https://pandoc.org/MANUAL.html#syntax-highlighting
It is also mentioned R Markdown Definitive guide for revealjs: https://bookdown.org/yihui/rmarkdown/appearance-and-style-1.html#appearance-and-style-1

Did you try that already ?

**Comment by cderv** [comment] 2021-10-06 18:13
Duplicate of #92

**Closed** 2021-10-06 18:13 UTC
